# Stage 1: Build the Vue application
FROM node:22-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Copy the .env.production as .env
COPY .env.production .env

RUN npm run build

# Stage 2: Serve the app with Nginx
FROM nginx:stable-alpine AS production-stage
RUN rm -rf /usr/share/nginx/html/*
# Copy the built files
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Copy your custom Nginx configuration file
COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
