server {
    listen 80;
    server_name localhost;  # This is internal to the container

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Try to serve the requested file; if not found, serve index.html
        try_files $uri $uri/ /index.html;
    }
}
