FROM nginx:stable-alpine

# Clean default config
RUN rm -f /etc/nginx/conf.d/default.conf

# Accept nginx config dynamically via build args
ARG NGINX_CONF=nginx.preprod.conf
COPY ${NGINX_CONF} /etc/nginx/conf.d/default.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
